# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{snippets_converter}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nowhere Man"]
  s.date = %q{2011-02-08}
  s.default_executable = %q{snippets_converter}
  s.description = %q{Quick and dirty code to transform TextMate Snippets into Gedit, NetBeans and Ruble (Aptana Studio) snippets}
  s.email = %q{nowhereman@open_office}
  s.executables = ["snippets_converter"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/snippets_converter",
    "in/DummyFile",
    "lib/snippets_converter.rb",
    "lib/snippets_converter/editors/gedit.rb",
    "lib/snippets_converter/editors/netbeans.rb",
    "lib/snippets_converter/editors/ruble.rb",
    "out/DummyFile",
    "snippets_converter.gemspec",
    "test/examples/assert_bad_value.tmSnippet",
    "test/test_helper.rb",
    "test/test_parse_tm_snippet.rb",
    "test/test_snippets_converter.rb"
  ]
  s.homepage = %q{http://github.com/nowhereman/snippets_converter}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Convert TextMate Snippets Gedit, NetBeans and Ruble (Aptana Studio) Snippets.}
  s.test_files = [
    "test/test_helper.rb",
    "test/test_parse_tm_snippet.rb",
    "test/test_snippets_converter.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["< 3.0.0"])
    else
      s.add_dependency(%q<activesupport>, ["< 3.0.0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["< 3.0.0"])
  end
end

